services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    labels:
      container-name: math-service
    ports:
      - "8080:8080"
    volumes:
      - ../:/production